apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mygk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mygk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mygk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mygk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mygk
    spec:
      containers:
      - image: quay.io/jentesting/rhtap-demo-ziwq-tenant/rhtap-demo-app/hacbs-test-project-mygk@sha256:60adb49af596847f9b2c2f3253636e45e6028241aa0fe7fe02a075d7175d1a1b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
